{
 "title": "custom dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "dcgm_instance",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,instance)"
    }
   },
   { "name": "gpu", "query": { "query": "label_values(gpu)" } },
   {
    "name": "nginx_instance",
    "query": {
     "query": "label_values(nginx_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX Status for $nginx_instance",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "repeat": "nginx_instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$nginx_instance\"}"
    }
   ]
  },
  {
   "title": "CPU 사용률",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "CPU 사용률 추이",
   "type": "timeseries",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 5, "w": 14, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "메모리 사용률",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "메모리 사용률 추이",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100",
     "legendFormat": "RAM {{ram}}"
    }
   ]
  },
  {
   "title": "GPU 사용률",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"${dcgm_instance}\", gpu=~\"${gpu}\"}"
    }
   ]
  },
  {
   "title": "GPU 사용률 추이",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"${dcgm_instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM 클럭",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"${dcgm_instance}\", gpu=~\"${gpu}\"} * 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 메모리 사용률",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (DCGM_FI_DEV_FB_USED / (DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE))"
    }
   ]
  },
  {
   "title": "GPU 메모리 사용량",
   "type": "stat",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED / 1024" }
   ]
  },
  {
   "title": "컨테이너 별 CPU 사용률",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{name=~\".*th5-ocr.*\"}[5m]) * 100\r\nunless ignoring(name) absent(container_cpu_user_seconds_total{name=~\".*th5-ocr.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{instance=~\"$nginx_instance\"}[5m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  }
 ]
}