version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9333:9333 # ui
    command: "master -ip=master -ip.bind=0.0.0.0"
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8080:8080 # http
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8888:8888 # ui
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8333:8333 # s3 api http
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0'
    depends_on:
      - master
      - volume
      - filer
