services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine-v13.12.0
    container_name: gitlab-runner
    restart: always
    volumes:
      - ./gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
