version: '3.8'

services:
  oraclelinux:
    build:
      context: .
    container_name: oracle
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - 31092:31092