services:
  db:
    container_name: postgres_dev
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image_produce
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
