services:
  db:
    container_name: postgres_dev
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image_produce
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - postgres_volume:/var/lib/postgresql

volumes:
  postgres_volume:
