stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .next/cache/
install:
  image: node:18
  stage: install
  script:
    - npm ci

build:
  image: node:18
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - out/
  dependencies:
    - install

deploy:
  image: docker
  stage: deploy
  script:
    - docker compose down || true
    - docker compose up --build -d
  only:
    - master
  dependencies:
    - build
