image: node:18-alpine

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .next/cache/
    - .npm/

install:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline
  only:
    - gitlab-ci

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - out/
  dependencies:
    - install
  only:
    - gitlab-ci

deploy:
  image: docker:26.1.3
  stage: deploy
  script:
    - docker compose down || true
    - docker compose up --build -d
  dependencies:
    - build
  only:
    - gitlab-ci
