services:
  easy-train:
    container_name: easy-dev
    build: .
    environment:
      - TZ=Asia/Seoul
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    stdin_open: true
    tty: true
