services:
  flask:
    container_name: ${CONTAINER_NAME}
    build:
      context: ${CONTEXT_PATH}
      dockerfile: Dockerfile
      args:
        APP_DIR: ${WORK_DIR}
    ports:
      - ${EXPOSED_PORT}:${INTERNAL_PORT}
    volumes:
      - .:${WORK_DIR}
    networks:
      - flask_network
    env_file:
      - .env

networks:
  flask_network:
    name: ${NETWORK_NAME}
    external: true
