services:
  wjh-ppocr:
    image: paddlepaddle/paddle:3.0.0-gpu-cuda11.8-cudnn8.9-trt8.6
    container_name: wjh-ppocr
    ipc: host
    network_mode: "bridge"
    stdin_open: true
    tty: true
    volumes:
      - .:/paddle_custom
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
