networks:
  app-tier:
    driver: bridge

services:
  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    ports:
      - "9094:9094"
      - "59094:59094"
    networks:
      - app-tier
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@:9093
      # 클라이언트의 메타데이터 최초 요청을 받는 포트
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:59094
      # 클라이언트에 응답하는 실제로 접근해야 하는 엔드포인트 (PLAINTEXT: 내부, EXTERNAL: 외부)
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://ggomg.duckdns.org:59094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

    volumes:
      - $HOME/kafka_data:/bitnami/kafka
