networks:
  app-tier:
    driver: bridge

services:
  kafka-broker-1:
    image: "bitnami/kafka:latest"
    container_name: kafka-broker-1
    ports:
      - "9094:9094"
      - "59094:59094"
    networks:
      - app-tier
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:59094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-broker-1:9092,EXTERNAL://ggomg.duckdns.org:59094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - $HOME/kafka_data_1:/bitnami/kafka

  kafka-broker-2:
    image: "bitnami/kafka:latest"
    container_name: kafka-broker-2
    ports:
      - "9095:9095"
      - "59095:59095"
    networks:
      - app-tier
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:59095
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-broker-2:9092,EXTERNAL://ggomg.duckdns.org:59095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - $HOME/kafka_data_2:/bitnami/kafka

  kafka-broker-3:
    image: "bitnami/kafka:latest"
    container_name: kafka-broker-3
    ports:
      - "9096:9096"
      - "59096:59096"
    networks:
      - app-tier
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:59096
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-broker-3:9092,EXTERNAL://ggomg.duckdns.org:59096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - $HOME/kafka_data_3:/bitnami/kafka
