networks:
  app-tier:
    driver: bridge

services:
  kafka-broker-1:
    image: "bitnami/kafka:latest"
    container_name: kafka-broker-1
    ports:
      - "29094:29094"
    networks:
      - app-tier
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=test-multi-broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:29094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-broker-1:9092,EXTERNAL://ggomg.duckdns.org:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_NUM_PARTITIONS=6
    volumes:
      - kafka_data_1:/bitnami/kafka

  kafka-broker-2:
    image: "bitnami/kafka:latest"
    container_name: kafka-broker-2
    ports:
      - "29095:29095"
    networks:
      - app-tier
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=test-multi-broker
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:29095
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-broker-2:9092,EXTERNAL://ggomg.duckdns.org:29095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_NUM_PARTITIONS=6
    volumes:
      - kafka_data_2:/bitnami/kafka

  kafka-broker-3:
    image: "bitnami/kafka:latest"
    container_name: kafka-broker-3
    ports:
      - "29096:29096"
    networks:
      - app-tier
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=test-multi-broker
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:29096
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-broker-3:9092,EXTERNAL://ggomg.duckdns.org:29096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_NUM_PARTITIONS=6
    volumes:
      - kafka_data_3:/bitnami/kafka

volumes:
  kafka_data_1:
  kafka_data_2:
  kafka_data_3:
