services:
  fast-api:
    container_name: ${CONTAINER_NAME}
    build:
      context: ${CONTEXT_PATH}
      dockerfile: Dockerfile
      args:
        APP_DIR: ${WORK_DIR}
    ports:
      - ${EXPOSED_PORT}:${INTERNAL_PORT}
    volumes:
      - .:${WORK_DIR}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - .env
